apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.fullname" . }}-1-init-sqldump-pemfiles-sh-configmap
  labels:
    app: {{ include "mysql.fullname" . }}
data:
  1-init-sqldump-pemfiles-sh-configmap.sh: |
    cp -f /mysql-pem-files/* /mysql_datadir/mysql_live_data/mysql || true
    echo -e '\n mysql pem files copied\n'

    cp -f /mysql_sqldump/* /docker-entrypoint-initdb.d || true
    echo -e '\n mysql dump files copied\n'

    # innodb cluster creation script , this will execute only when mysql service is started
    echo -e '\n starting innodb cluster creation script in nohup, this will execute only when mysql service is started\n'
    nohup bash -ch "bash /mnt/init-innodb-cluster.sh" > /mnt/init-innodb-cluster.log 2>&1 &
