apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.fullname" . }}-common-cnf-configmap
  labels:
    app: {{ include "mysql.fullname" . }}-inno-cluster
data:
  common.cnf: |
    [mysqld]

    default-authentication-plugin=mysql_native_password
    #default-time-zone='Asia/Tokyo'
    log_timestamps=SYSTEM

    user=mysql

    skip-host-cache
    skip-name-resolve
    #skip-slave-start

    datadir=/mysql_datadir/mysql_live_data/mysql
    socket=/mysql_datadir/mysql_live_data/mysql_db.socket

    secure_file_priv=/mysql_datadir/mysql_files
    pid-file=/var/run/mysqld/mysqld.pid


    port={{ .Values.mysqlport.port }}
    mysqlx_port={{ .Values.mysqlport.mysqlx }}
    admin_port={{ .Values.mysqlport.mysqladmin }}


    enforce_gtid_consistency=ON
    gtid_mode=ON

    expire_logs_days    = {{ .Values.innodbConfig.expireLogsDays }}

    bind-address        = *
    log_bin             = /mysql_datadir/mysql_live_data/binlog/mysql-bin.log
    log_bin_index       = /mysql_datadir/mysql_live_data/binlog/mysql-bin.log.index
    relay_log           = /mysql_datadir/mysql_live_data/binlog/mysql-relay-bin
    relay_log_index     = /mysql_datadir/mysql_live_data/binlog/mysql-relay-bin.index
    binlog_checksum=NONE         
    slave_preserve_commit_order=ON

    binlog_format       = ROW
    max_binlog_size     = 100M
    log_slave_updates   = 1
    # slave-skip-errors= 1062,1146,1215,1072,1265

    max_allowed_packet= 1024M
    max_connections =  {{ .Values.innodbConfig.maxConnections }}
    max_user_connections =  {{ .Values.innodbConfig.maxUserConnections }}
    group_concat_max_len=100000000
    log_error_verbosity=3

    #CHAR SET
    character_set_server=utf8mb4
    collation_server=utf8mb4_0900_ai_ci

    #INNODB ENGINE
    innodb_buffer_pool_size = {{ .Values.innodbConfig.innodbBufferPoolSize }}
    innodb_buffer_pool_instances = {{ .Values.innodbConfig.innodbBufferPoolInstances }}
    innodb_old_blocks_pct   = 50
    innodb_old_blocks_time  = 0
    innodb_read_io_threads={{ .Values.innodbConfig.innodbReadIOThreads }}
    innodb_write_io_threads={{ .Values.innodbConfig.innodbWriteIOThreads }}
    innodb_temp_data_file_path = ibtmp1:12M:autoextend:max:{{ .Values.innodbConfig.innodbTempDataFilePathSize }}
    innodb_print_all_deadlocks = 1
    binlog_transaction_dependency_tracking=WRITESET

    sql_mode=STRICT_ALL_TABLES
    thread_cache_size=18
    federated

    net_read_timeout=30
    interactive_timeout=1800
    connect_timeout=10

    local-infile=0
    skip-grant-tables = FALSE
    master_info_repository=TABLE
    relay_log_info_repository=TABLE
    allow-suspicious-udfs=FALSE
    log-raw=OFF

    # OVERCOME SLAVE LAG
    slave_parallel_workers  =   {{ .Values.innodbConfig.slaveParallelWorkers }}
    slave_parallel_type     =   LOGICAL_CLOCK

    performance-schema-instrument='wait/lock/metadata/sql/mdl=ON'

    performance-schema-instrument='transaction=ON'
    performance-schema-consumer-events-transactions-current=ON
    performance-schema-consumer-events-transactions-history=ON
    performance-schema-consumer-events-transactions-history-long=ON

    slow-query-log=1
    long_query_time=10
    slow_query_log_file=/mysql_datadir/mysql_logs/slow_query.log
    log_slow_extra=1

    [mysqldump]
    max_allowed_packet=1024M
    quick
    compress

    [client]
    socket=/mysql_datadir/mysql_live_data/mysql_db.socket
    default-character-set=utf8mb4
    
    [xtrabackup]
    open-files-limit=2000000
