apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.fullname" . }}-pmm-setup-configmap
  labels:
    app: {{ include "mysql.fullname" . }}-inno-cluster
data:
  pmm_setup.sh: |
    echo '############# Starting External Services#############'
    
    echo 'Configuring PMM Agent'
    pmm-agent setup --config-file=/pmm-agent.yml  --server-address={{ .Values.pmmConfig.serverIP}}:{{ .Values.pmmConfig.serverPort}} --server-insecure-tls --server-username=admin --server-password=admin localhost container $HOSTNAME --force || true

    echo 'Starting PMM Agent '
    nohup pmm-agent --config-file=/pmm-agent.yml > /pmm-agent-nohup.log 2>&1 &
    
    sleep 15;
    echo 'Adding MySQL Service to PMM Agent'
    pmm-admin add mysql --query-source=perfschema --username=pmm_agent --password='pmmA@gnt' --service-name="$INFRA_K8s_CLUSTERNAME-$HOSTNAME" --socket=/mysql_datadir/mysql_live_data/mysql_db.socket || true

    echo '#############starting external services completed#############'
