apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.fullname" . }}-extraconfig-configmap
  labels:
    app: {{ include "mysql.fullname" . }}-router
data:
  router-extraconfig.conf: |
    [http_server]
    port=8443
    bind_address=::0
    ssl=0
    #ssl_cert=/tmp/mysqlrouter/data/router-cert.pem
    #ssl_key=/tmp/mysqlrouter/data/router-key.pem


    [http_auth_backend:default_auth_backend]
    backend=file
    filename=/etc/mysqlrouter/mysqlrouter.pwd

