apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.fullname" . }}-healthcheck-sh-configmap
  labels:
    app: {{ include "mysql.fullname" . }}-router
data:
  healthcheck.sh: |
    #!/bin/bash

    # The mysql-init-complete file is touched by the entrypoint file before the
    # main server process is started

    if [ -f /mysql-router-init-complete ]; # The entrypoint script touches this file
      then # Ping server to see if it is ready
      mysqladmin --defaults-extra-file=/healthcheck.cnf ping
    else # Initialization still in progress
      exit 1
    fi
