apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}-router
  labels:
    app: {{ include "mysql.fullname" . }}-router
spec:
  selector:
    app: {{ include "mysql.fullname" . }}-router
  type: NodePort
  ports:
  - name: mysql
    port: {{ .Values.routercontainer.port }}
   # nodePort: 30022
    protocol: TCP
  - name: mysqlro
    port: {{ .Values.routercontainer.roport }}
   # nodePort: 30022
    protocol: TCP
  - name: mysqlx
    port: {{ .Values.routercontainer.port }}1
   # nodePort: 30020
    protocol: TCP
  - name: mysqladmin
    port: {{ .Values.routercontainer.port }}2
   # nodePort: 30021
    protocol: TCP
  - name: mysqlapi
    port: {{ .Values.routercontainer.apiport }}
   # nodePort: 30021
    protocol: TCP
