apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.fullname" . }}-server-key-configmap
  labels:
    app: {{ include "mysql.fullname" . }}-router
data:
  server-key.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDRTIEYspa8A8ag
    68oliI/xeje/tMXxLmRdUGLbBm5sjMvAw5lNY2ksl/ViGN65cZg95F3AKS4XwkfM
    GXMHLQfSzqaxuaFHXeNYa9FOQw1epL78lzNwB9KWA1DM8kkDUkqQSSXwVjjUTqHJ
    5JW+cSBqPoaMM/5ykpfOPjsNHm6VXruYKLcsOhFF4U0J2dU8SUVam703ZDFEqIqb
    +R1ewuN0mp4KExdAG756tLeiujTnqT41FM1INR1dhMqJWSp7KjAcztfec+p2nPbB
    jxViF8OVPOxyX20Jouw5uxA34+HtjPG9g9si1+tQHkZk9DusvBItm6ednOH5QofW
    +KGDC7/pAgMBAAECggEAZAlI+uEBIsQ7P9bzO5VWF3jvBHYG1gvydJdjaIReawuw
    p2XV9CM7tdC7vDNe4QvmVE6+cIY+PaTiZC8Vx6xCPQQAsJmk+FNrwmtmEx4BWecs
    UdaDA1z5zjGvgQWc2DWQ5f3QYFsVtoQO2EylNe0kLSPNc122lFR0smMUHmUZPdK3
    9S6P5zyTcZAX50aARjFIVDkcnTsOvBnBAJmXB4PN1dZLSjfQLSZlMhBkDooxRTTU
    YD+24udxT5lIqnYqVvJ8wlJPhgO7an919W7t3gQBxsY3tCt85V6dTxaq8qkbQPuN
    BbVvbx23DzIuSQY8UCRS4Jttrm0zBElNKX/Au/sMcQKBgQD1oeBMN9wODLc3kLnU
    XKPf9C/CWJXgqmJSXRQjhSJoydaVX2t48pARoq7bvkEAHx8Sp+NHxEkd1x1r5Gt9
    nGS0BF9IkItbe+JK5qtOT/QupKsIommm4V23R+7ExIeCcDBJI/Xz/NX0u1FQp/eP
    0a9E6oIBywMviRup6x5txZbSAwKBgQDaIgj03IgpWxF9EyS26/2KwMysAGG/68SX
    rtapGGb/ghj8y7ZXnjR4Xyce4lzlzsyVn6my/8zXnh2u1hrIIAPcXNUEK6efkWjH
    FDjHY9mjK4szZPhpzKSCu/Tx9zOXmjRuyuWil4AAFjZoW6FSqAPJhxxG6B60Bx1G
    1c+5DfFYowKBgHztm9qn/m/W38iO/zSW+XIKC9BYpcHiZqdlV7zJFbseDNlj8pFN
    LSELEMwKc5zQN0mRwfLaTiWzJu+c+V6lkEJOhvetLHOXCnz13OKzn4mpjqORlxKd
    RMDXAQVqv1EEJkrM02cIjPkv3CedhjfLec0fSIgI7NHcdglx38QM3qxpAoGAQZ9j
    mmaOAAMJq9sKfI1aZVfDOyuSPK6tIgTTR2Oz+MImykZuwMUze9MEbeIjmG8yVQEH
    iHY0JdnHjEWVIQegoba7ztljQDn6j4mh2zpKyy/aXMfPg+SwyTPKaNC5kK4vf/VC
    SDvTojMMgzCtw7QQD5y6AQrr0bUiNaE1MLLlHIkCgYEAskKjvsFZg36ADzxrlAR5
    Yl7tHwKnhHIJrZK1zvnqBsPwXQcZG7ry72mWTmsqE1mL/PVuWkjZyf609rMx24UO
    48ukDnVY9sZMU9zGKGMwoVn9fMY9DRkSnpltTalwQFzEdUA4E0+RvG3zdXaPRe67
    yGi4WHJs36iv7jbMLASRZAY=
    -----END PRIVATE KEY-----
    
    

